### PR TITLE
Added Carthage support

### PR DESCRIPTION
**Pull request by almassapargali**
Separated HCSStarRatingView.{h|m} to framework project, and added to sample project as dependency. Cocoapods will continue working as is.

### CODE REVIEW

**Comment by hugocampossousa** [comment]
Hi @almassapargali! Thanks for your PR adding support for Carthage.

I looked around and it seems ok. I just had one request: could you please remove the tests target and files, since they're not required in this library?

If you don't have time it's ok, I can remove it after merging.

Thanks again!

**Comment by almassapargali** [comment]
Yep, sure.

**Comment by almassapargali** [comment]
Done.

**Comment by hugocampossousa** [comment]
Hi @almassapargali! I tested your solution and the only thing missing is what I wrote in the comment above.

If you want I can merge the PR and make the change afterwards.

Thanks for spotting the bug and helping out with the fix! :+1:

**Pull request merged**
