### PR TITLE
Add Podspec and note about installation to Readme

### PR DESCRIPTION
**Pull request by ScottWarner**
I kinda guessed at the iOS version support, I put >= 6.0 in the Podspec.
If you decide to keep this, it would be great if you could tag the library and update the version line to match the tag.

Note: I haven't made a podspec before, this was essentially copied from another project and modified to fit yours.

### CODE REVIEW

**Comment by ScottWarner** [comment]
Addresses #1 too

**Comment by ScottWarner** [comment]
Hold on - getting an error: 'Failed to load Designables from path (null), might have misconfigured the podspec

**Comment by ScottWarner** [comment]
Interface builder is all borked up with pods. See https://github.com/CocoaPods/CocoaPods/issues/2792

You could merge this, but it may cause more headache explaining why it wont work in IB than its worth.
Closing because of this

**Comment by hugocampossousa** [comment]
Hi @ScottWarner!

I agree with you, merging this would cause more headache than it's actually worth.

Thanks for your help, though!

**Comment by hugocampossousa** [comment]
Hi again @ScottWarner.

I ended up merging another pull request and included some information you added here.

Thanks again for your help, hope you like the control!

**Pull request closed without merging**
